import type { Product } from "./types";

export const products: Product[] = [
  // Destaques
  {
    id: "combo-kumo",
    name: "Combo Kumo - 24 pecas",
    description: "Sashimi - 5 Un Salmao gomayaki, 5 Un Atum gomayaki; Nigiri - 4 Un Aburi salmao, 3 Un Skin, 3 Un Jow; Uramaki - 4 ebitem",
    price: 29.90,
    originalPrice: 59.80,
    image: "/images/combo1.webp",
    category: "destaques",
    pieces: 24,
  },
  {
    id: "combo-hikari",
    name: "Combo Hikari - 32 pecas",
    description: "8 Un Uramaki salmao, 8 Un Hot roll, 8 Un Jow maki, 4 Un Nigiri salmao, 4 Un Sashimi salmao",
    price: 39.90,
    originalPrice: 79.80,
    image: "/images/combo2.webp",
    category: "destaques",
    pieces: 32,
  },
  {
    id: "combo-imperador",
    name: "Combo Imperador - 48 pecas",
    description: "12 Un Hot roll, 8 Un Uramaki skin, 8 Un Philadelphia, 8 Un Jow maki, 6 Un Sashimi salmao, 6 Un Nigiri variados",
    price: 54.90,
    originalPrice: 109.80,
    image: "/images/combo3.webp",
    category: "destaques",
    pieces: 48,
  },
  {
    id: "combo-bushido",
    name: "Combo Bushido - 40 pecas",
    description: "10 Un Sashimi salmao, 10 Un Hot roll, 8 Un Philadelphia, 6 Un Nigiri salmao, 6 Un Uramaki especial",
    price: 49.90,
    originalPrice: 99.80,
    image: "/images/combo4.webp",
    category: "destaques",
    pieces: 40,
  },
  // Combinados Especiais
  {
    id: "combinado-salmao",
    name: "Combinado Salmao Premium - 16 pecas",
    description: "8 Un Sashimi salmao fresco, 4 Un Nigiri salmao, 4 Un Uramaki salmao",
    price: 44.90,
    originalPrice: 89.80,
    image: "/images/combo5.webp",
    category: "combinados",
    pieces: 16,
  },
  {
    id: "combinado-macaricado",
    name: "Combinado Macaricado - 44 pecas",
    description: "Selecao especial de pecas macaricadas com molho da casa",
    price: 64.90,
    originalPrice: 129.80,
    image: "/images/combo6.webp",
    category: "combinados",
    pieces: 44,
  },
  {
    id: "combinado-prime",
    name: "Combinado Prime - 58 pecas",
    description: "O melhor do sushi em uma selecao premium com variedade de pecas especiais",
    price: 79.90,
    originalPrice: 159.80,
    image: "/images/combo7.webp",
    category: "combinados",
    pieces: 58,
  },
  // Yakisobas
  {
    id: "yakisoba-tradicional",
    name: "Yakisoba Tradicional",
    description: "Macarrao frito com legumes, frango e carne bovina ao molho especial",
    price: 32.90,
    originalPrice: 45.90,
    image: "/images/yakisoba1.webp",
    category: "yakisobas",
  },
  {
    id: "yakisoba-camarao",
    name: "Yakisoba de Camarao",
    description: "Macarrao frito com camaroes frescos, legumes e molho oriental",
    price: 42.90,
    originalPrice: 59.90,
    image: "/images/yakisoba2.webp",
    category: "yakisobas",
  },
  {
    id: "yakisoba-salmao",
    name: "Yakisoba de Salmao",
    description: "Macarrao frito com cubos de salmao grelhado e legumes frescos",
    price: 44.90,
    originalPrice: 62.90,
    image: "/images/yakisoba3.webp",
    category: "yakisobas",
  },
];

export const categories = [
  { id: "destaques", name: "Destaques" },
  { id: "combinados", name: "Combinados Especiais" },
  { id: "yakisobas", name: "Yakisobas" },
];
